### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp_mako#2]
I need to release ``aiohttp_mako`` first in order release ``aiohttp_debugtoolbar``. My plan is following
1) discuss and resolve #1 
2) add basic documentations
3) add one more advanced example

Thoughts?

**Comment by asvetlov** [comment]
Please feel free to release at any moment -- documentation and examples may be added later if you have no time right now.

**Comment by jettify** [comment]
Released to pypi: https://pypi.python.org/pypi/aiohttp_mako
