### ISSUE TITLE
Decorator function doesn't get the request correctly if there are other args.

### ISSUE THREAD

**Issue by neRok-** [aio-libs/aiohttp_mako#3]
There is currently the line `request = args[-1]` at line 77 of \__init__.py, inside `def wrapper`. If my view function has other args after the request arg, it tries to use the last one as the request. Should this line of code be changed to `request = args[0]`?

Further to this, should it also support kwargs?

**Comment by asvetlov** [comment]
What's your use case?

`aiohttp_mako.template` decorator supposed to be used with *aiohttp web-handlers* only.
*web-handler* accepts the only `request` parameter -- that's how *aiohttp.web* works.
If you really need something non-standard please invite your own decorator which uses `render_template` function internally.

**Comment by neRok-** [comment]
I doubt I am doing it right, but I was attempting to return the get function for a route after an unsuccessful post, and pass some messages etc in the process. I suppose I should be attaching them to the request session first, or something similar.

**Comment by asvetlov** [comment]
Yes, code example would be useful.

**Comment by neRok-** [comment]
Here is a simplified example of a login route that accepts GET and POST.

```
import asyncio
from aiohttp.web import HTTPFound
import aiohttp_mako

@asyncio.coroutine
@aiohttp_mako.template('login.html')
def get(request, message=None):
    return {'message': message}

@asyncio.coroutine
def post(request):
    post = yield from request.post()
    try:
        # Get the user and validate the password, raise Exception if not correct.
    except Exception:
        message = 'The supplied username and password were not correct.'
        response = yield from get(request, message=message)
        return reponse
    # Add the user to the session etc, and return to home page.
    return HTTPFound(request.app.router['home'].url())
```
Just thinking about your comment *"web-handler accepts the only request parameter"*. If this is the case, why is the wrapped function using `*args`?
```
def wrapped(*args):
    #<snip>
    context = yield from coro(*args)
    request = args[-1]
```
Would the following be more appropriate?
```
def wrapped(request):
    #<snip>
    context = yield from coro(request)
```

**Comment by asvetlov** [comment]
The only reason for accepting `*args`: web-handler  shaped as method should have a different signature: it accepts `(self, request)`.
